"""add fk and cascade to refresh_token.user_id

Revision ID: e33b75983d6e
Revises: 3417468e95c5
Create Date: 2026-04-08 22:40:23.928563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33b75983d6e'
down_revision: Union[str, Sequence[str], None] = '3417468e95c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'refreshtoken', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refreshtoken', type_='foreignkey')
    # ### end Alembic commands ###
