"""add cascade delete to page_tag_link

Revision ID: 3417468e95c5
Revises: ff6c455ff432
Create Date: 2026-04-08 22:24:34.796119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3417468e95c5'
down_revision: Union[str, Sequence[str], None] = 'ff6c455ff432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pagetaglink_page_id_fkey'), 'pagetaglink', type_='foreignkey')
    op.drop_constraint(op.f('pagetaglink_tag_id_fkey'), 'pagetaglink', type_='foreignkey')
    op.create_foreign_key(None, 'pagetaglink', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pagetaglink', 'page', ['page_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pagetaglink', type_='foreignkey')
    op.drop_constraint(None, 'pagetaglink', type_='foreignkey')
    op.create_foreign_key(op.f('pagetaglink_tag_id_fkey'), 'pagetaglink', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('pagetaglink_page_id_fkey'), 'pagetaglink', 'page', ['page_id'], ['id'])
    # ### end Alembic commands ###
